name: Build and push Cronjobbed-rclone Image

on:
  push:
    tags:
      - 'v*'

env:
  BWS_DOCKERHUB_USERNAME: ebf9ede7-b7eb-422f-a590-b16c014a70a3
  BWS_DOCKERHUB_TOKEN: 0fa21e12-63ae-4793-a9a5-b16c014aa15d
  DOCKER_IMAGE_NAME: adnanjaw/cronjobbed-rclone
  SUPPORTED_PLATFORMS: 'linux/amd64, linux/arm64, linux/arm/v7'
  LATEST_TAG: latest
  TEST_TAG: test

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Fetch Secrets From BWS
        uses: bitwarden/sm-action@v2.0.0
        with:
          access_token: ${{ secrets.BWS_TOKEN }}
          secrets: |
            ${{ env.BWS_DOCKERHUB_USERNAME }}  > DOCKERHUB_USERNAME
            ${{ env.BWS_DOCKERHUB_TOKEN }} > DOCKERHUB_TOKEN
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}
      -
        name: Build and export to Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: '${{ env.DOCKER_IMAGE_NAME }}:${{ env.TEST_TAG }}'
#      - name: Test docker image before push
#        run: |
#          docker run --rm -e CRON_EXPRESSION='* * * * *' '${{ env.DOCKER_IMAGE_NAME }}:${{ env.TEST_TAG }}'
#        continue-on-error: true
      - name: Build and push latest
        if: success()
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: ${{ env.SUPPORTED_PLATFORMS }}
          push: true
          tags: '${{ env.DOCKER_IMAGE_NAME }}:${{ env.LATEST_TAG }}'
      -
        name: Build and push v.x.x
        if: success()
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: ${{ env.SUPPORTED_PLATFORMS }}
          push: true
          tags: '${{ env.DOCKER_IMAGE_NAME }}:${{ github.ref_name }}'
